### ISSUE TITLE
GitHub REST API Request Quota Exceeded

### ISSUE THREAD

**Issue by will-v-pi** [paulober/vscode-raspberry-pi-pico#33]
After creating lots of projects in a short space of time, the warning "Request quota exhausted for request GET /repos/{owner}/{repo}/releases" comes up. Looking at https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28 the rate limit for unauthenticated users is only 60 per hour from one ip, so with 3 requests per project that can be hit relatively easily, especially in a larger organisation.

Could we cache these requests locally and then follow the guidance at https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#use-conditional-requests-if-appropriate to make conditional requests, as the data won't change very often so this should keep us under the rate limit?

Also, we could add the option for users to add an authenticated token in the settings somewhere, and then make authenticated requests if a token is provided, as the limit for those is 5000 per hour. However, generating these tokens would have to be a manual job for users.

**Comment by will-v-pi** [comment]
The cache doesn't seem to be working for me - the api is always returning with code 500 for the sdk version (and sometimes for the ninja version) when I'm making unauthenticated requests. Does this happen for you too? When I made authenticated requests it works for the SDK and ninja, but CMake seems to have a different etag every time so it never reads from the cache

**Comment by paulober** [comment]
I have the same issue if no access token is provided. I'm working on it.

**Comment by paulober** [comment]
@will-v-pi Sorry for the inconvenience. I now manually implemented the api access and bypassing the library GitHub develops. Now it should work as intended and with support for GitHub personal access tokens.

(Though I discovered using PATs does take noticeably longer. It may be the vscode api to retrieve the setting or GitHub for verifying the token.)

**Comment by will-v-pi** [comment]
Thanks for this, it's now working fine. Although one annoying thing I've noticed is that the release data includes a download count, which means that the etag will change every time someone downloads the release assets, so the cache will only last until someone else downloads the item (which is quite regularly for cmake).

Not an issue for now, but might be worth revisiting at a later stage to see if there's another way
