### ISSUE TITLE
`CYW43_WL_GPIO_LED_PIN` undefined by intellisense

### ISSUE THREAD

**Issue by paulober** [paulober/vscode-raspberry-pi-pico#38]
If I open the picow_blink example I get intellisense warning `identifier "CYW43_WL_GPIO_LED_PIN" is undefined` even though if I CMD+Left click on it I get referred to `<PICO_SDK>/src/boards/include/boards/pico_w.h`.

@will-v-pi Do we may want to add this header to forceInclude if the board type pico_w is selected during project generation?

**Comment by paulober** [comment]
(Note to my self: This would also require to add the board type selector back to the webview and the generator if isImport)

**Comment by paulober** [comment]
I now added it to dynamically use the board type to add this forceInclude. If importing projects it takes it from the CMakeLists.txt and for examples it scans the key of the project in the examples.json for "picow" or "pico_w" and if it finds one it adds pico_w board type.

This is just for testing. I'm not sure for examples to rely on the examples key as it could be omitted and only supports pico or picow if maybe other boards are supported in the future this would maybe not be the most future proofed solution.

And I'm not sure if this force include is the right way to go also for the pico.h....

Here is the commit I added: d98e45ac53b9e0c25510fb53f710038f3811e8b6

**Comment by will-v-pi** [comment]
Ah, this'll be related to the other intellisense issue I noticed, where it was including the wrong pico.h file. I'll have a play tomorrow, but I think it just needs a forced include of config_autogen.h which is generated in the build directory, as that's where the actual include of the correct board is put
